### ISSUE TITLE
Capturing performance.marks / performance.measure 

### ISSUE THREAD

**Issue by NasarTarique** [grafana/faro-web-sdk#118]
## Description

Having faro capture the performance.marks and performance.measure and sending it as a trace for certain custom events/ actions would make it easier to measure and track  the user activity . 

## Proposed solution

Add an instrumentation for capturing  performance.mark/measure info 

## Context
[performance.measure](https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure)

**Comment by codecapitano** [comment]
Hi @NasarTarique thanks a lot for your participation and ideas.

We already started to work on instrumenting auto capture of Performance, Navigation and Resource timings (#112 ).
We will very likely build the feature in a way that users can choose  to add more `entryTypes` to be observed and captured (by default we will not add many of the, because this may negatively impact client performance).

If you need that kind of functionality immediately you can either implement a custom instrumentation or [add functionality to your app which captures performance entries](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver#examples), such as marks and measurements, and [use Faros push* APIs to send the data  to your endpoint](https://grafana.com/docs/grafana-cloud/faro-web-sdk/custom-signals/).


See also: [https://grafana.com/docs/grafana-cloud/faro-web-sdk/faro-web-sdk-components/provided-instrumentations/](https://grafana.com/docs/grafana-cloud/faro-web-sdk/faro-web-sdk-components/provided-instrumentations/)

**Comment by codecapitano** [comment]
@NasarTarique We just released an **experimental** [instrumentation to capture performance timeline events](https://www.npmjs.com/package/@grafana/faro-instrumentation-performance-timeline).
It offers an option to define which events it should capture. 

The README shows an example how to capture `mark` and `measure`.
