### ISSUE TITLE
Trace ID not being added to logs?

### ISSUE THREAD

**Issue by cg-roling** [grafana/faro-web-sdk#143]
I followed the Getting Started guide, and I can see my logs/exceptions and my traces, but I'm not seeing any way to correlate the two. Should the traceId be automatically set on the logs?

My end goal is to be able to see the context around an exception in a single trace: navigation, http requests, clicks, logs, the exception, etc up until the next navigation.

Is there something I need to do to get that all correlated?

**Comment by codecapitano** [comment]
Hi @cg-roling thank you for opening the issue. 

Could you please provide more info about how you initialized Faro for example?

This would help to quickly find out if it is a config issue or if the problem lays elsewhere.
For example: Did you add the `TracingInstrumentation and so on.

 Cheers, 
 Marco

**Comment by cg-roling** [comment]
For sure, I think it's pretty much straight from the guide. This is an Angular app, I'm starting it inside a service, possibly it needs to be started earlier in the process?

```
    // Initialize Grafana Faro
    this.faro = initializeFaro({
      url: "https://faro-collector-prod-us-central-0.grafana.net/collect/<redacted>",
      app: {
        name: "<redacted>",
        version: this.appInfoService.getMajorMinorPatchVersion(),
        environment: "dev",
      },
      instrumentations: [
        new ErrorsInstrumentation(),
        // Mandatory, overwriting the instrumentations array would cause the default instrumentations to be omitted
        ...getWebInstrumentations(),
        // Mandatory, initialization of the tracing package
        new TracingInstrumentation(),
      ],
    });
```

**Comment by codecapitano** [comment]
Hi @cg-roling 

The init code looks good. 
One tiny thing: you don't need to instantiate the `ErrorsInstrumentation` because it's already instantiated with calling `getWebInstrumentations()`.

Regarding when to initialize the SDK:
[We recommend to initialize it before any other code](https://grafana.com/docs/grafana-cloud/faro-web-sdk/get-started/#add-the-grafana-faro-web-sdk-package-using-npm-registry) (as mentioned in step 2 of the linked doc).

Regrading your issue:
Currently we can not guarantee that Trace or SpanIDs will be added because it happens that spans are already ended when signals occur. So we can not correlate them with their respective traces. 
At the moment your best option in that cases is SessionId + order in time. 

When it comes to tracing `fetch` or `xmlHttpRequests` please be aware that URLs are ignored for tracing.
This is to prevent instruments reporting in a loop on themselves.
For example the collector URL defined in in the `app: {url: …}` property is automatically excluded. 
(`url: "https://faro-collector-prod-us-central-0.grafana.net/collect/<redacted>"`)

**Comment by cg-roling** [comment]
Ok, I think I understand. Once the `documentLoad` span has finished, there won't be a traceId available to attach to the logs.

I'm attempting to create my own span to correlate logs and errors to, and I'm still not having any luck. The following code creates a span that I can find in the Explore tab of Grafana, but it doesn't appear to have any relation to the error, event, or logs:


    const { trace, context } = faro.api.getOTEL();
    const tracer = trace.getTracer("default");
    const span = tracer.startSpan("CUSTOM SPAN");

    context.with(trace.setSpan(context.active(), span), () => {
      faro.api.pushLog(["TEST PUSH LOG IN SPAN"]);
      faro.api.pushEvent("TEST EVENT IN SPAN");
      faro.api.pushError(new Error("TEST ERROR IN SPAN"));
    });


Is there something further I need to do to associate the log/event/error to the span?

**Comment by codecapitano** [comment]
Hi,

your code is fine so far. 
Tested it with our demo app and it worked well.

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/47627413/231402780-e2fceac0-ac67-4c91-bf8d-29a44821ca2d.png">

I added the test code to the[ file which is initializing Faro](https://github.com/grafana/faro-web-sdk/blob/6c0022c18f93a1a3b7f3b063ab8687d0c11378e8/demo/src/client/faro/initialize.ts#L14-L15) to see if it works.

```ts

 // ...

export function initializeFaro(): Faro {
     const faro = coreInit({...})
   
    const { trace, context } = faro.api.getOTEL()!;
    const tracer = trace.getTracer('default');
    const span = tracer.startSpan('CUSTOM SPAN');

    context.with(trace.setSpan(context.active(), span), () => {
      faro.api.pushLog(['TEST PUSH LOG IN SPAN']);
      faro.api.pushEvent('TEST EVENT IN SPAN');
      faro.api.pushError(new Error('TEST ERROR IN SPAN'));
    });
  });

 // ...
}
```

**Comment by cg-roling** [comment]
Thanks for the ongoing help, I'm still wrapping my head around Grafana in general 😅

Looks like the logs are indeed getting correlated, and I can link to the trace from the Explore view in Grafana:
![image](https://user-images.githubusercontent.com/108348028/232161954-bc0380b8-650e-41d4-8ed8-957ef6206aa4.png)

The error seems to be getting a trace_id, but for some reason there's no link in the Explore view:
![image](https://user-images.githubusercontent.com/108348028/232162031-fac90515-eb4d-4287-8f28-b528710bebfa.png)

I suspect that must be a problem at a different level, so I'll go ahead and close this issue. Thanks!
