### ISSUE TITLE
Enhancing WebVitalInstrumentation with Additional Information

### ISSUE THREAD

**Issue by vitebo** [grafana/faro-web-sdk#593]
## Description

Currently, the WebVitalInstrumentation only sends the metric value. However, in many cases, it would be highly beneficial to include additional data to aid in debugging.

## Proposed Solution

I propose that the SDK should offer two versions of WebVitalInstrumentation. The enhanced version would provide more detailed WebVitals information, utilizing the ['web-vitals/attribution'](https://github.com/GoogleChrome/web-vitals?tab=readme-ov-file#send-attribution-data) feature.

This enhanced instrumentation was initially developed for an internal company project due to the absence of such a feature. Considering its broad applicability, I believe incorporating it into this SDK would be beneficial. I am eager to contribute this solution if there is community interest.

**Comment by codecapitano** [comment]
Thanks so much @vitebo 
I have thought about this for some time as well and consider attribution data this as very valuable. Didn't tackle it due to conflicting priorities. So a contribution would be amazing.

Great initiative, looking forward to your PR 🙏 

PS: 
I am on vacation next week so don't wonder if it takes a bit till I answer.
But @eskirk and @cedricziel can help if you've any questions in the meantime.

PPS:
Out of curiosity, did you build any custom visualizations for web-vitals + attribution data?

Cheers,
Marco

**Comment by vitebo** [comment]
Thank you, Marco!

I think I can work on it this weekend.

> Out of curiosity, did you build any custom visualizations for web-vitals + attribution data?

We haven't built anything very elaborate yet. Creating the visualizations is scheduled for our next sprint. Currently, we only have a basic dashboard that identifies the page elements causing poor INP, which has been our main issue.

<details>
  <summary>INP visualization preview</summary>
  
  https://github.com/grafana/faro-web-sdk/assets/19560693/b33c818f-6222-49dd-a45d-92313c970857

</details>

There's still a lot of room for improvement in the visualization shown in the video above. Once we create better visualizations for web vitals + attribution, I would love to come back and share our results here.

**Comment by codecapitano** [comment]
Hey André thanks for sharing love it.

> I think I can work on it this weekend.

Take all the time you need. It may happen that the review process may take a bit longer as usual due to vacation season.

May I ask another question since your team is working on tackling performance things 🎉 
Du you also use our navigation / resource timings instrumentation?

**Comment by vitebo** [comment]
Not yet. We adopted Grafana Faro recently (less than a month ago), so we are gradually connecting the instrumentations.
As feedback, when I first saw the folder for this [performance instrumentation](https://github.com/grafana/faro-web-sdk/tree/main/packages/web-sdk/src/instrumentations/performance), I thought it might still be in testing phase because I couldn't find any mentions of it in the [instrumentation documentation](https://grafana.com/docs/grafana-cloud/monitor-applications/frontend-observability/architecture/instrumentations/#provided-instrumentations).

**Comment by codecapitano** [comment]
Hey @vitebo 
Ah got it. This is because we are currently in the process of restructuring the docs.
You will find the docs here: [Track navigation and resource performance](https://grafana.com/docs/grafana-cloud/monitor-applications/frontend-observability/instrument/performance-instrumentation/#track-navigation-and-resource-performance)

**Comment by vitebo** [comment]
solved here https://github.com/grafana/faro-web-sdk/pull/595
