### ISSUE TITLE
RUM -  Safari - Mozilla Faro Logs are coming in as unknown

### ISSUE THREAD

**Issue by Elangovanse** [grafana/faro-web-sdk#596]
Hi Team,

Could you please help us that "event_data_responseStatus=unknown" instead of 200 only for safari and Firefox browser. Why Faro is not supporting how we can fix this issue or any alternate solution to address it. Your earlier resposne is much grateful

Safari/Firefox Log: 

timestamp="2024-05-09 06:59:51.249 +0000 UTC" kind=event event_name=faro.performance.resource event_domain=browser event_data_cacheHitStatus=fullLoad event_data_decodedBodySize=0 event_data_dnsLookupTime=0 event_data_duration=887 event_data_encodedBodySize=0 event_data_faroNavigationId=59wmZ8inGn event_data_faroResourceId=kxxkjhXZam event_data_fetchTime=887 event_data_initiatorType=fetch
event_data_name=https://XXXXXXXXXXXXX
event_data_redirectTime=0 event_data_renderBlockingStatus=unknown event_data_requestTime=0 event_data_responseStatus=unknown event_data_responseTime=12441 event_data_serviceWorkerTime=11554 event_data_tcpHandshakeTime=0 event_data_tlsNegotiationTime=0 sdk_version=1.7.2 
app_name=XXXXXXXXXXXX
app_version=0.0.1 
app_environment=local-sdk 
session_id=XXXXXXXXXX
page_url=https://XXXXXXXXXXXXX
browser_os="Windows 10" browser_mobile=false view_name=default

Regards,
Sangeetha

**Comment by Elangovanse** [comment]
Hi Team,

Any update on this?

**Comment by codecapitano** [comment]
Hi @Elangovanse 

The behavior is correct and expected. 
[The `responseStatus` property is currently only available in Chrome based browsers](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/responseStatus#browser_compatibility).
We still decided to add it because since Chrome based browsers have such a wide market share it adds value to provide the property even with the current restrictions.

From our docs—[Track navigation and resource performance](https://grafana.com/docs/grafana-cloud/monitor-applications/frontend-observability/instrument/performance-instrumentation/#track-navigation-and-resource-performance):

> responseStatus: the HTTP response status code returned when fetching a resource. This property is not available in Firefox and Safari and is set to unknown for those browsers.
